import React from 'react';
import { Apple, Droplets, Flame, Utensils, CheckCircle, Info, Sparkles } from 'lucide-react';

function Corners({ color = "border-[#C9A15A]" }) {
  return (
    <>
      <span className={`absolute -top-px -left-px w-3 h-3 border-t border-l ${color}`} />
      <span className={`absolute -top-px -right-px w-3 h-3 border-t border-r ${color}`} />
      <span className={`absolute -bottom-px -left-px w-3 h-3 border-b border-l ${color}`} />
      <span className={`absolute -bottom-px -right-px w-3 h-3 border-b border-r ${color}`} />
    </>
  );
}

function Eyebrow({ children }) {
  return (
    <span className="inline-flex items-center gap-2 font-mono text-[11px] tracking-[0.14em] uppercase text-[#C9A15A]">
      <span className="w-3.5 h-px bg-[#C9A15A] inline-block" />
      {children}
    </span>
  );
}

const NutritionViewer = ({ plan }) => {
  if (!plan) {
    return (
      <div className="flex flex-col items-center justify-center text-center py-24 border border-dashed border-white/10 relative bg-[#18170F]/40">
        <Corners color="border-white/15" />
        <div className="w-14 h-14 border border-white/15 flex items-center justify-center mb-6 bg-[#131210]">
          <Apple size={22} className="text-white/25" />
        </div>
        <h3 className="font-display text-xl text-slate-100">No Nutrition Plan Assigned</h3>
        <p className="text-[#A79E8E] text-sm max-w-sm mt-2.5 leading-relaxed">
          Your custom dietary macros and meal plans will be displayed here once generated by your coach.
        </p>
      </div>
    );
  }

  const {
    title,
    goal,
    targetCalories = 2400,
    targetMacros = { proteinGrams: 160, carbsGrams: 250, fatsGrams: 65 },
    waterLitersPerDay = 3.5,
    meals = [],
    guidelines = [],
    trainer,
  } = plan;

  // Calculate macro calorie percentages
  const proteinCals = targetMacros.proteinGrams * 4;
  const carbsCals = targetMacros.carbsGrams * 4;
  const fatsCals = targetMacros.fatsGrams * 9;
  const totalCalculatedCals = proteinCals + carbsCals + fatsCals || targetCalories;

  const proteinPct = Math.round((proteinCals / totalCalculatedCals) * 100) || 30;
  const carbsPct = Math.round((carbsCals / totalCalculatedCals) * 100) || 45;
  const fatsPct = Math.round((fatsCals / totalCalculatedCals) * 100) || 25;

  return (
    <div className="space-y-6">
      {/* Header & Daily Target Summary Banner */}
      <div className="relative border border-[#6FBE8C]/30 p-6 md:p-7 bg-[#18170F]/60 overflow-hidden">
        <Corners color="border-[#6FBE8C]" />
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-5 relative z-10">
          <div>
            <div className="flex items-center gap-2.5 mb-2">
              <span className="font-mono text-[10.5px] uppercase tracking-wide text-[#6FBE8C] border border-[#6FBE8C]/30 px-2 py-0.5 bg-[#131210]">
                {goal}
              </span>
              <span className="font-mono text-[10.5px] uppercase tracking-wide text-[#A79E8E]">
                Daily Protocol
              </span>
            </div>
            <h3 className="font-display text-2xl text-slate-100 leading-snug">{title}</h3>
          </div>

          {trainer && (
            <div className="flex items-center gap-3 p-3 border border-white/10 bg-[#131210] shrink-0">
              <div className="w-9 h-9 rounded-full border border-[#6FBE8C]/40 bg-[#1D1B16] flex items-center justify-center font-display text-[#6FBE8C] text-sm">
                {trainer.name?.charAt(0) || 'N'}
              </div>
              <div className="text-left">
                <p className="font-mono text-[10px] uppercase tracking-wider text-[#6E6858]">Diet Specialist</p>
                <p className="text-xs font-medium text-slate-200">{trainer.name}</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Target Macro Pillars (4 Grid matching STATS) */}
      <div className="grid grid-cols-2 lg:grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">
        {/* Calories */}
        <div className="group relative border border-white/10 p-5 bg-[#18170F]/60 overflow-hidden transition-all hover:border-white/25">
          <Corners color="border-[#FF4B2B]/40" />
          <div className="absolute top-0 left-0 right-0 h-[2px] bg-[#FF4B2B] opacity-70" />
          <div className="flex items-start justify-between mb-4">
            <span className="font-mono text-[10.5px] uppercase tracking-wide text-[#6E6858]">Daily Target</span>
            <div className="w-8 h-8 border border-[#FF4B2B]/30 flex items-center justify-center bg-[#FF4B2B]/10">
              <Flame size={14} className="text-[#FF4B2B]" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="font-display text-3xl text-slate-100">{targetCalories}</span>
            <span className="font-mono text-xs text-[#A79E8E]">kcal</span>
          </div>
          <div className="mt-3 pt-2.5 border-t border-dashed border-white/10 font-mono text-[10.5px] text-[#6E6858]">
            Energy baseline
          </div>
        </div>

        {/* Protein */}
        <div className="group relative border border-white/10 p-5 bg-[#18170F]/60 overflow-hidden transition-all hover:border-white/25">
          <Corners color="border-[#4FD1C5]/40" />
          <div className="absolute top-0 left-0 right-0 h-[2px] bg-[#4FD1C5] opacity-70" />
          <div className="flex items-start justify-between mb-4">
            <span className="font-mono text-[10.5px] uppercase tracking-wide text-[#6E6858]">Protein ({proteinPct}%)</span>
            <div className="w-8 h-8 border border-[#4FD1C5]/30 flex items-center justify-center bg-[#4FD1C5]/10">
              <Utensils size={14} className="text-[#4FD1C5]" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="font-display text-3xl text-[#4FD1C5]">{targetMacros.proteinGrams}</span>
            <span className="font-mono text-xs text-[#A79E8E]">grams</span>
          </div>
          <div className="mt-3 pt-2.5 border-t border-dashed border-white/10 font-mono text-[10.5px] text-[#6E6858]">
            Muscle recovery &amp; growth
          </div>
        </div>

        {/* Carbs */}
        <div className="group relative border border-white/10 p-5 bg-[#18170F]/60 overflow-hidden transition-all hover:border-white/25">
          <Corners color="border-[#C9A15A]/40" />
          <div className="absolute top-0 left-0 right-0 h-[2px] bg-[#C9A15A] opacity-70" />
          <div className="flex items-start justify-between mb-4">
            <span className="font-mono text-[10.5px] uppercase tracking-wide text-[#6E6858]">Carbohydrates ({carbsPct}%)</span>
            <div className="w-8 h-8 border border-[#C9A15A]/30 flex items-center justify-center bg-[#C9A15A]/10">
              <Sparkles size={14} className="text-[#C9A15A]" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="font-display text-3xl text-[#C9A15A]">{targetMacros.carbsGrams}</span>
            <span className="font-mono text-xs text-[#A79E8E]">grams</span>
          </div>
          <div className="mt-3 pt-2.5 border-t border-dashed border-white/10 font-mono text-[10.5px] text-[#6E6858]">
            Glycogen &amp; endurance fuel
          </div>
        </div>

        {/* Hydration */}
        <div className="group relative border border-white/10 p-5 bg-[#18170F]/60 overflow-hidden transition-all hover:border-white/25">
          <Corners color="border-[#6FBE8C]/40" />
          <div className="absolute top-0 left-0 right-0 h-[2px] bg-[#6FBE8C] opacity-70" />
          <div className="flex items-start justify-between mb-4">
            <span className="font-mono text-[10.5px] uppercase tracking-wide text-[#6E6858]">Daily Hydration</span>
            <div className="w-8 h-8 border border-[#6FBE8C]/30 flex items-center justify-center bg-[#6FBE8C]/10">
              <Droplets size={14} className="text-[#6FBE8C]" />
            </div>
          </div>
          <div className="flex items-baseline gap-2">
            <span className="font-display text-3xl text-[#6FBE8C]">{waterLitersPerDay}</span>
            <span className="font-mono text-xs text-[#A79E8E]">Liters / day</span>
          </div>
          <div className="mt-3 pt-2.5 border-t border-dashed border-white/10 font-mono text-[10.5px] text-[#6E6858]">
            Cellular hydration &amp; health
          </div>
        </div>
      </div>

      {/* Meals Breakdown */}
      <div className="space-y-4 pt-2">
        <div>
          <Eyebrow>Daily Structure</Eyebrow>
          <h4 className="font-display text-2xl text-slate-100 flex items-center gap-2 mt-1">
            <Utensils size={18} className="text-[#C9A15A]" />
            <span>Prescribed Meal Schedule ({meals.length} Meals)</span>
          </h4>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-1 sm:grid-cols-2 gap-4">
          {meals.map((meal, idx) => (
            <div
              key={idx}
              className="p-5 border border-white/10 bg-[#18170F]/70 space-y-4 relative hover:border-[#C9A15A]/30 transition-colors"
            >
              <Corners color="border-white/15" />
              <div className="flex items-center justify-between pb-3 border-b border-white/10">
                <span className="font-display text-base font-bold text-[#C9A15A]">
                  {meal.mealType}
                </span>
                <span className="font-mono text-[11px] uppercase tracking-wider px-2.5 py-1 bg-[#131210] border border-white/10 text-slate-300">
                  {meal.time}
                </span>
              </div>

              <div className="space-y-2.5">
                {meal.items?.map((item, i) => (
                  <div
                    key={i}
                    className="p-3 bg-[#131210]/90 border border-white/5 flex items-center justify-between text-xs"
                  >
                    <div>
                      <p className="font-medium text-slate-200">{item.name}</p>
                      <p className="font-mono text-[10px] text-[#A79E8E] mt-0.5">{item.portion}</p>
                    </div>
                    <div className="text-right font-mono">
                      <span className="text-[#F5F1E8] font-bold">{item.calories} kcal</span>
                      <p className="text-[10.5px] text-[#6FBE8C] mt-0.5">
                        {item.protein}g P · {item.carbs}g C
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              {meal.notes && (
                <p className="text-xs text-[#A79E8E] italic pt-1 border-t border-dashed border-white/10">
                  Note: {meal.notes}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Guidelines & Rules */}
      {guidelines && guidelines.length > 0 && (
        <div className="p-5 border border-[#C9A15A]/30 bg-[#18170F]/70 relative space-y-3">
          <Corners color="border-[#C9A15A]" />
          <h5 className="font-display text-base text-slate-100 flex items-center gap-2">
            <Info size={16} className="text-[#C9A15A]" />
            <span>Trainer Nutritional Guidelines &amp; Rules</span>
          </h5>
          <ul className="space-y-2 text-xs sm:text-sm text-[#A79E8E]">
            {guidelines.map((g, idx) => (
              <li key={idx} className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 rounded-full bg-[#C9A15A] mt-1.5 shrink-0" />
                <span className="leading-relaxed">{g}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default NutritionViewer;
